### PR TITLE
Fix deleting issue

### LINKED ISSUE #1: Issue removes from list only after page is refreshed
### Bug description
Deleted issue is still displaying in issues list and it disappear only after page is refreshed.

### To Reproduce

1. Open issues list.
2. Click on "Delete" button on any issue.
3. Deleted issue is still displaying in issues list.
4. Refresh current page - deleted issue is not displaying anymore.

### Expected behavior
Deleted issue should not be displayed in issues list straight away without page reloading.

### PR DESCRIPTION
**Pull request by vopos**
Fixes #1.

### CODE REVIEW

File: src/main.js [hunk 1]
```diff
@@ -42,6 +42,8 @@ function deleteIssue(id) {
   }
 
   localStorage.setItem('issues', JSON.stringify(issues));
+
+    fetchIssues();
```
Comment (ehaberev) [inline src/main.js]: @vopos, please lint your code! See CONTRINBUTING.md for details.

Comment (vopos) [reply src/main.js]: @ehaberev, done!
